app:
  scheduler:
    enable: true
    interval: 7500
    force-check-delay: 7500
  database-access-type: jpa

clients:
  connection:
    attempts: 3
    delay: 5
    timeout: 5
    strategy: linear
    codes: [500, 502, 503, 504]
  urls:
    github: https://api.github.com
    stackoverflow: https://api.stackexchange.com
    bot: http://localhost:8090

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    password: postgres
    username: postgres
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: swagger-ui
