app:
  scheduler:
    enable: true
    interval: 7500
    force-check-delay: 7500
  database-access-type: jpa

clients:
  connection:
    attempts: 3
    delay: 5
    timeout: 5
    strategy: linear
    codes: [500, 502, 503, 504]
  urls:
    github: https://api.github.com
    stackoverflow: https://api.stackexchange.com
    bot: http://localhost:8090

spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    password: postgres
    username: postgres
  application:
    name: scrapper

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: (/tg-chat.*)|(/links.*)
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - execute-condition: "getRemoteAddr() == '127.0.0.1'"
          cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10000
              time: 1
              unit: minutes
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10
              time: 1
              unit: minutes

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: swagger-ui
