app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

urls:
  github: https://api.github.com
  stackoverflow: https://api.stackexchange.com

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
