app:
  scheduler:
    enable: true
    interval: 7500
    force-check-delay: 7500

urls:
  github: https://api.github.com
  stackoverflow: https://api.stackexchange.com
  bot: http://localhost:8090

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
